- neptune-export/docs/create-pg-config.md
- neptune-export/docs/export-pg-from-config.md
- neptune-export/docs/export-pg-from-queries.md
- neptune-export/docs/export-pg.md
- neptune-export/docs/export-rdf.md
- neptune-export/readme.md
- neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportBaseCommand.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/auth/ConnectionConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NeptuneGremlinClient.java
*Description of changes:* Provide `--use-ssl` option. This will allow connecting to Neptune using SSL. Note that this cannot be used with a network load balancer. If you are using a load balancer you must use SSL termination and have your own SSL certificate on the proxy server. A network load balancer, being a Layer 4 load balancer, doesn't support SSL termination.
> Provide `--use-ssl` option

- neptune-export/pom.xml
- neptune-export/src/main/java/com/amazonaws/services/neptune/io/KinesisStreamOutputWriter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/io/OutputWriter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/io/PrintOutputWriter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/io/Target.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/EdgesClient.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/GremlinQueryDebugger.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NodesClient.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/Range.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/RangeFactory.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPropertyGraphPrinter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/JsonPropertyGraphPrinter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NeptuneStreamsJsonPropertyGraphPrinter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphExportFormat.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/EnhancedNQuadsWriter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/EnhancedTurtleWriter.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/NeptuneStreamsJsonNQuadsWriter.java
All ops for a commit for Gremlin submitted as a single JSON array record to Kinesis to preserve unit of work semantics necessary for ElasticSearch index population scripts.
> Improvements to exporting Neptune Stream records to Kinesis

- drop-graph/drop-graph.py
Unable to connect to Neptune writer over ws://
Changed socket url to use secure websocket (wss://) instead of ws://
> use wss:// instead of ws://

- neptune-python-utils/build.sh
- neptune-python-utils/neptune_python_utils/endpoints.py
- neptune-python-utils/neptune_python_utils/glue_gremlin_client.py
- neptune-python-utils/neptune_python_utils/glue_neptune_connection_info.py
- neptune-python-utils/readme.md
*Issue #, if available:* 33, 53
*Description of changes:* Previously, insert/upsert operations in Glue jobs proceeded one vertex or edge at a time. Now they can be submitted in batches, thereby improving throughput. (Batch size is 1, by default, for backwards compatability). Operations will retry up to 5 times if a ConcurrentModifcationException occurs.
This PR also allows for IAM credentials to be refreshed periodically in long-running Glue jobs.
> Support batch inserts/upserts in Glue jobs, with retries.

- neptune-gremlin-client/gremlin-client-demo/src/main/java/com/amazonaws/services/neptune/RefreshAgentDemo.java
- neptune-gremlin-client/gremlin-client/src/main/java/com/amazonaws/services/neptune/cluster/ClusterEndpointsRefreshAgent.java
- neptune-gremlin-client/readme.md
Simplify ClusterEndpointsRefreshAgent by passing EndpointsSelector into constructor rather than each method.
> Initialize agent with selector

- neptune-export/pom.xml
- neptune-export/readme.md
Add 'Best practices' section to readme.
Update jackson-databind in pom to prevent issues with AWS SDK looking for field PASCAL_CASE_TO_CAMEL_CASE, which has been removed in later versions of jackson-databind.
> Update Neptune Export readme

- csv-gremlin/README.md
- csv-gremlin/csv-gremlin.py
Adds a command line option to control whether `datetime` or `new Date()` style dates are generated in the Gremlin queries.
> Add support to control date formatting

- csv-gremlin/README.md
- csv-gremlin/csv-gremlin.py
- csv-gremlin/test.csv
- Added an option to limit the number of CSV rows that are processed.
- Added an option to specify how dates with no TZ info are processed (can assume UTC or local time) when generating Java style dates.
- Tightened up some edge cases in date processing overall to ensure dates always have a TZ. This fixes an issue when trying to compare naive and non-naive dates.
- The ~label column in vertex CSV files is now optional and a default of 'vertex' will be used.
- Updated the README.
> Csv gremlin updates

- csv-gremlin/README.md
- csv-gremlin/csv-gremlin.py
- csv-gremlin/test-files/edges-with-repeat-ids.csv
- csv-gremlin/test-files/vertices-with-repeat-ids.csv
- Allow the same ID to appear on more than one row of a vertex defining CSV file
- Add an end of processing summary report
- Add an option to disable the summary report
- Fix an issue where single 'g' elements were generated for edge rows containing errors
- Add more error detection for edge files
- Add tests that cover repeating ID values
> Csv gremlin repeating ids

- neptune-python-utils/neptune_python_utils/gremlin_utils.py
In TinkerPop 3.5.0 the Tornado transport layer was removed from the library. This pull request modifies the Python gremlin-utils file to remove references to `gremlin_python.driver.tornado`, and (slightly) modifies the code to work with the new AIOHTTP transport layer.
This pull request also updates the code in line with apache/tinkerpop#1329, allowing per-request options in the session client (the missing keyword argument was previously causing an error).
Thank you all for the useful resources in this repo!
> Remove Tornado, for gremlin-python 3.5 compatibility

- neptune-python-utils/neptune_python_utils/endpoints.py
*Issue #, if available:* https://github.com/awslabs/amazon-neptune-tools/issues/134
> Make LazyHttpHeaders iterable

- neptune-streams-utils/examples/java8/src/main/java/stream_handler/StreamHandler.java
Additional param within Environment variable for Lambda is set as neptune_cluster_endpoint - https://github.com/awslabs/amazon-neptune-tools/blob/master/neptune-streams-utils/provisioning/provision_neptune_streams_handler.py#L156
Hence, renaming neptune_endpoint to neptune_cluster_endpoint.
Connection to neptune cluster was failing from Lambda during initialisation. Renaming additional param set as part of environment variable from neptune_endpoint to neptune_cluster_endpoint fixed the issue. 
> Corrected additional parameter key name

- neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CommonConnectionModule.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/CloneCluster.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/ConnectionConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/ProxyConfig.java
> Support proxy endpoint and port

- export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json
A new version of Neptune to ES processing is released in order to support new OpenSearch versions. Need to update path of lambda artifacts to point to new versions.
*Issue #, if available:* https://github.com/awslabs/amazon-neptune-tools/issues/185
*Description of changes:* 
Made a change in underlying module used which was blocking requests to new OpenSearch versions.
> Update path for Neptune to ES export artifacts

- neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportCommand.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/RunNeptuneExportSvc.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/export/ExportToS3NeptuneExportEventHandler.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportLambda.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportRunner.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportService.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphJob.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphTask.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/LabelWriters.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/ExportSpecification.java
An AWS customer reported an issue with the default value of 9000 being used for MaxFileDescriptorCount causing failure in exporting their graph containing a large number of unique labels and edges. 
[For AWS employees, see CR-68158508 for more context]
Instead of a static value for MaxFileDescriptorCount ([code pointer](https://github.com/awslabs/amazon-neptune-tools/blob/b93899ffb0b05a528f968f92467b06c597b046e4/neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/LabelWriters.java#L27)), currently 9000, pass the value from neptune-export service and use that as the MaxFileDescriptorCount after removing buffer, thus making the value configurable for customers via CFN template available at …
> make MaxFileDescriptorCount configurable for neptune-export service

- neptune-gremlin-client/gremlin-client-demo/pom.xml
- neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RefreshAgentDemo.java
- neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RollingSubsetOfEndpointDemo.java
- neptune-gremlin-client/gremlin-client/pom.xml
- neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/GremlinClusterBuilder.java
- neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/LBAwareHandshakeInterceptor.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromLambdaProxy.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApi.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneGremlinClusterBuilder.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/utils/RegionUtils.java
- neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
- neptune-gremlin-client/pom.xml
- neptune-gremlin-client/readme.md
version upgrade to TinkerPop 3.5.2 for gremlin-client 1.0.4.
> Bump to TinkerPop 3.5.2

- export-neptune-to-elasticsearch/lambda/requirements.txt
*Issue #, if available:* #224
- Updated Lambda artifact dependencies for the `export-neptune-to-elasticsearch` tool. This brings the dependency versions in line with the upgrades to the Lambda layer for Python 3.9 (#223).
> Update Lambda dependencies for Neptune-ES export tool

- csv-gremlin/README.md
- csv-gremlin/csv-gremlin.py
- csv-gremlin/test-files/header-with-spaces-edge.csv
- csv-gremlin/test-files/header-with-spaces.csv
#229 
Provide a new option to trim leading spaces in CSV header and data rows unless wrapped in quotes. This better matches the behavior of the Neptune bulk loader. Note that this PR does not attempt to address trailing spaces. The Python DictReader provides no way to know if a string was quoted or not and only has an option to skip leading spaces. So for now I have adapted that and do not attempt to trim trailing spaces.
> Handle leading spaces correctly #229

- export-neptune-to-elasticsearch/lambda/README.md
- export-neptune-to-elasticsearch/lambda/build.sh
- export-neptune-to-elasticsearch/lambda/requirements.txt
Issue #, if available:  Issue #226
Description of changes:  
Changed aws-kinesis-agg dependency to version 1.1.7. 
Added build script and README.md with build instructions.
> [export-neptune-to-elasticsearch] [Issue 226] Changed aws-kinesis-agg dependency to version 1.1.7. 

- neptune-python-utils/readme.md
Updating README self-supplied credentials example to encourage use of the Credentials object rather than ReadOnlyCredentials. Using ReadOnlyCredentials will throw an Exception on line 110 in endpoints.py, as it has no get_frozen_credentials() method 
> Update example for self-supplied credentials

- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/AddCloneTask.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/NeptuneClusterMetadata.java
With engine 1.2.0.0, Neptune introduced a new parameter group family, neptune1.2. neptune-export had previously been hard-coded with neptune1 when cloning a cluster. Now, the tool determines the correct family.
> Determine correct parameter group family when cloning cluster.

- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/NeptuneClusterMetadata.java
For Neptune Export Service installs that don't have the requisite IAM permissions to query the cluster parameter group, infer the necessary parameter family from the engine version number.
> Infer parameter group family for old Neptune Export Service installs

- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/GetLastEventId.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/NeptuneClusterMetadata.java
- neptune-export/src/test/java/com/amazonaws/services/neptune/cluster/GetLastEventIdTest.java
neptune-export will infer the last commit num for cloned clusters where Neptune Streams is enabled. This fix allows the tool to infer the last commit num for Neptune engines older than 1.0.4.2.
> Fix issue parsing last commit num for engines < 1.0.4.2

- neptune-gremlin-client/readme.md
*Description of changes:* The Neptune Gremlin Client includes an AWS Lambda function that proxies endpoint information, thereby reducing the number of calls to the Neptune Management API. This PR updates the readme with details of this Lambda function.
> Neptune gremlin client 8 11 2022

- neptune-gremlin-client/gremlin-client-demo/pom.xml
- neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/lambda/NeptuneGremlinClientExampleLambda.java
- neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RefreshAgentDemo.java
- neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RollingSubsetOfEndpointDemo.java
- neptune-gremlin-client/gremlin-client/pom.xml
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/ClusterEndpointsRefreshAgent.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/ClusterMetadataFetchStrategy.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsSelector.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsType.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromLambdaProxy.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApi.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneClusterMetadata.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneInstanceMetadata.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/OnNewClusterMetadata.java
- neptune-gremlin-client/gremlin-client/src/test/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApiTest.java
- neptune-gremlin-client/gremlin-client/src/test/java/software/amazon/neptune/cluster/NeptuneClusterMetadataTest.java
- neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
- neptune-gremlin-client/neptune-endpoints-info-lambda/src/main/java/software/amazon/lambda/NeptuneEndpointsInfoLambda.java
- neptune-gremlin-client/pom.xml
- neptune-gremlin-client/readme.md
This change adds support for using custom endpoint selectors with a ClusterEndpointsRefreshAgent querying an AWS Lambda endpoints proxy. Previously, when using a ClusterEndpointsRefreshAgent with a Lambda proxy, you could only select endpoints using an EndpointsType enum. Now, with custom selector support, you can get a list of instances in your cluster from the Lambda proxy based on tags, instance types, instance IDs, AZs, etc.
> Refresh agent for Lambda proxy now allows custom endpoint selectors

- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApi.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneInstanceMetadata.java
Instance info return by DescribeDbInstances that are in a 'creating' state may not have an endpoint. This fix checks for null endpoints when creating NeptuneInstanceMetadata from a DescribeDbInstancesResult.
> Check for null endpoints on instance metadata.

- neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/ExportRdfGraph.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/RemoveClone.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CloneClusterModule.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CommonConnectionModule.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/CloneCluster.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/Cluster.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/ConnectionConfig.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/DoNotCloneCluster.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/GetLastEventIdTask.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/NeptuneClusterMetadata.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/RemoveCloneTask.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/SimulatedCloneCluster.java
- neptune-export/src/main/java/com/amazonaws/services/neptune/profiles/incremental_export/IncrementalExportEventHandler.java
Previously, neptune-export used a simple heuristic to infer the cluster ID if the cluster ID wasn't supplied as an export parameter. With this change, given an endpoint address, the tool uses the Management API to infer the cluster ID. This is more robust than the previous solution.
> Improve inferring cluster ID from endpoint

- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/GremlinFilters.java
Issue #219 
When iterating through the gremlin filter steps, the call to `getTraversal()` would get the parent traversal.  This is problematic when there are multiple steps since, each step, will get the parent and then build the traversal from the root.  The end result is that the entire traversal will be repeated _n_ times, where _n_ is the number of steps in the query filter passed in.
Quick examples:
`hasLabel('Pet')`
```
__.V()
.hasLabel("Pet")
```
`hasLabel('Pet').or(hasLabel('Dog'), hasLabel('Cat'))`
```
__.V()
.hasLabel("Pet").or(__.hasLabel("Dog"),__.hasLabel("Cat"))
.hasLabel("Pet").or(__.hasLabel("Dog"),__.hasLabel("Cat))
```
From the queries I have been working with it appears that simply using the `whereTraversal` was sufficient to build out the graph traversal.
By submitting …
> Prevent duplication of gremlin filters

- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/DataType.java
- neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/io/CsvPropertyGraphPrinterTest.java
- neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/schema/DataTypeTest.java
Removed unescaping of double quotes before escaping them in CSV export, and added tests in CSVPropertyGraphPrinter to ensure proper escape of multiple adjacent double quotes. Also added tests for escaping newlines. 
Issue #, if available:
n/a
Description of changes:
An issue was found where String properties with adjacent double quotes were swallowed during export to CSV. e.g. a string data `"{"hello "World""}"`, should be escaped as `"{""hello ""World""""}"`, but will be escaped as `"{""hello ""World""}"` with one set of quotations missing after World.
The cause is this [line of code](https://github.com/awslabs/amazon-neptune-tools/blob/3960457cbccb5d19301d5a51172d3ac9668a31a1/neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/DataType.java#L381), which …
> Fix issue in Neptune Export to CSV where adjacent double quotes are swallowed

- neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphExportFormat.java
Fixes a bug whereby export jobs consisting of exporting raw JSON to a Kinesis Stream would not terminate upon completing the export.
> Fix export job hanging when exporting JSON to Kinesis Stream

- neptune-python-utils/readme.md
- [`graph-notebook>=3.0.7`](https://github.com/aws/graph-notebook/releases/tag/v3.0.7) supports at least `gremlinpython==3.5.1`: https://github.com/aws/graph-notebook/blob/main/setup.py#L69. Updating `neptune-python-utils` docs accordingly.
> Update neptune-python-utils docs about Neptune Workbench compatibility

- neptune-gremlin-client/gremlin-client/pom.xml
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsType.java
- neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneInstanceMetadata.java
- neptune-gremlin-client/readme.md
1.1.0: Instance endpoints will be considered available while the instance is updating.
Use 3.6.2 TinkerPop driver.
> 1.1.0: Use 3.6.2, and broader interpretation of isAvailable

- neptune-gremlin-client/readme.md
The Gremlin Client for Amazon Neptune has been migrated to a [new standalone repository](https://github.com/aws/neptune-gremlin-client). Ongoing development and releases will take place in the new repository, and this module here will no longer be maintained.
> Deprecation notice

- neptune-serverless-evaluator/README.md
- neptune-serverless-evaluator/pricing.py
Neptune serverless workload evaluator for provisioned instances currently does not produce expected result. Will address this as an issue in future releases. 
> removing provisioned workload evaluator

- neo4j-to-neptune/bin/neo4j-to-neptune.sh
Issue #365 
Description of changes:  Adding `neo4j-to-neptune.sh` wrapper script as is referenced in docs and in JAR file help.
Execute via `./bin/neo4j-to-neptune.sh` from the root directory of the Neo4j-to-Neptune utility after compiling the JAR file.
> Add neo4j-to-neptune.sh

- .github/workflows/neo4j-to-neptune-ci.yml
- neo4j-to-neptune/docs/bulk-load-config.md
- neo4j-to-neptune/docs/conversion-config.md
- neo4j-to-neptune/docs/convert-csv.md
- neo4j-to-neptune/docs/example-bulk-load-config.yaml
- neo4j-to-neptune/docs/example-conversion-config.yaml
- neo4j-to-neptune/pom.xml
- neo4j-to-neptune/readme.md
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/ConvertCsv.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/io/Neo4jStreamWriter.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/BulkLoadConfig.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/ConversionConfig.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/EdgeMetadata.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/Headers.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/Property.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/Token.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/VertexMetadata.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/util/CSVUtils.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/util/NeptuneBulkLoader.java
- neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/util/Utils.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/TestDataProvider.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/io/Neo4jStreamWriterIntegrationTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/io/Neo4jStreamWriterTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/metadata/BulkLoadConfigTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/metadata/ConversionConfigTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/metadata/EdgeMetadataTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/metadata/VertexMetadataTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/util/NeptuneBulkLoaderTest.java
- neo4j-to-neptune/src/test/java/com/amazonaws/services/neptune/util/UtilsTest.java
N/A
Main features added with this change:
- Added the ability to use the APOC CSV stream export from Neo4j driver
- Added the ability to update element labels/IDs, and to skip elements based on labels/IDs via YAML config
- Added the ability to call Bulk loading from the tool via YAML config
General workflow:
1.  If a file isn't supplied, streaming can be used where the driver will execute `CALL apoc.export.csv.all` and stream Neo4j data to specified directory
2. Conversion will be applied on the local files, along with any element label/ID updates configured, for which Neptune compatible CSV will be written to specified directory
3. If AWS credentials are supplied for Bulk loading, then the tool will attempt to compress the converted file …
> Neo4j Migration Tool utility updates
