awslabs/amazon-neptune-tools

graphml2csv/README.md
graphml2csv/graphml2csv.py

Adds support for alternate output file delimiters
Fixes inconsistent formatting: 
https://github.com/awslabs/amazon-neptune-tools/issues/4

Adds Python2/3 compatibility

---

graphml2csv/graphml2csv.py

Closes https://github.com/awslabs/amazon-neptune-tools/issues/8
Closes https://github.com/awslabs/amazon-neptune-tools/issues/6
* The xmlns for the graphml file is not specified.
* Node or edge elements do not have a label. It assumes node or edge for the label value.
* key elements do not have the 'for' attribute (assumes they are for both nodes and edges)
* Node IDs are not specified (uses node order number).
* Edge IDs are not specified (uses source_dest concatenation).

Updates graphml2csv script

---

neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/Export.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportFromQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportCli.java
neptune-export/src/main/java/com/amazonaws/services/neptune/graph/EdgesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/graph/NodesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/CsvPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/EdgeWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/EdgesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/ExportJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/ExportTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Format.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/GraphElementHandler.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/JsonPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/NodeWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/NodesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Printer.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/PropertyWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/QueriesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/QueryJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/QueryTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/QueryWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/WriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/metadata/DataType.java
neptune-export/src/main/java/com/amazonaws/services/neptune/metadata/MetadataSpecification.java

*Description of changes:* Allow export to JSON in addition to CSV

Add JSON export option

---

neptune-export/pom.xml
neptune-export/src/test/java/com/amazonaws/services/neptune/io/JsonPrinterTest.java

*Description of changes:* Update jackson-databind to 2.9.8

Update jackson-databind to 2.9.8

---

neptune-export/docs/create-pg-config.md
neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/docs/export-rdf.md
neptune-export/pom.xml
neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportRdfGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportBaseCommand.java
neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportCli.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/NeptuneSparqlClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/Prefixes.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/ExportRdfGraphJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/util/EnvironmentVariableUtils.java

*Description of changes:* Enable IAM DB Auth support in neptune-export

Enable IAM DB Auth support in neptune-export

---

neptune-export/docs/create-pg-config.md
neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/docs/export-rdf.md
neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportBaseCommand.java
neptune-export/src/main/java/com/amazonaws/services/neptune/auth/ConnectionConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/auth/HandshakeRequestConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/auth/LBAwareAwsSigV4ClientHandshaker.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NeptuneGremlinClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/NeptuneSparqlClient.java
neptune-export/src/main/java/org/apache/tinkerpop/gremlin/driver/LBAwareSigV4WebSocketChannelizer.java

*Description of changes:* Support connecting through a load balancer to a database with IAM DB Auth enabled

Support IAM DB Auth + NLB or ALB

---

neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/EdgesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/Format.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/JsonPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NodesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueriesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/WriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/PropertiesMetadata.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/PropertyTypeInfo.java

…rue)
*Description of changes:* Print ~label and ~id values if exporting from queries with valueMap(true)

Print ~label and ~id values when exporting from queries

---

neptune-export/docs/export-pg-from-queries.md
neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/PropertiesMetadata.java

*Description of changes:* Respect ordering in projections when exporting from queries

Respect ordering in projections when exporting from queries

---

neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/pom.xml
neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/ConcurrencyConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/EdgesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/ExportStats.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/GraphClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NeptuneGremlinClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NodesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/RangeFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/Scope.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/EdgeWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/EdgesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/DataType.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/MetadataSpecification.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/MetadataType.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/MetadataTypes.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/PropertiesMetadata.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/metadata/DataTypeTest.java

*Description of changes:* 
- Upgrade to Gremlin 3.4. 
- Use binary serialization. 
- Some performance improvements for edge queries. 
- Allow empty strings passed to a Date DataType to be returned unformatted.

Upgrade to Gremlin 3.4

---

neptune-export/docs/create-pg-config.md
neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/docs/export-rdf.md
neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportBaseCommand.java
neptune-export/src/main/java/com/amazonaws/services/neptune/auth/ConnectionConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NeptuneGremlinClient.java

Added options to adjust frame size via --max-content-length, and serializer

---

neptune-export/docs/export-pg.md
neptune-export/readme.md
neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/AllLabels.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/EdgesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/ExportStats.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/GraphClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/LabelsFilter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/MetadataSamplingSpecification.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NodesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/Scope.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/SpecifiedLabels.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/EdgeWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NodeWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NodesWriterFactory.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/CreateMetadataFromGraphSample.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/CreateMetadataFromGraphScan.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/ExportSpecification.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/GraphElementType.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/MetadataTypes.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/PropertiesMetadataCollection.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/TokensOnly.java

Performance and flexibility improvements to tokens-only export

---

neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CommonConnectionModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/GremlinQueryDebugger.java

Add header

---

drop-graph/drop-graph.py

Initial upload of the drop-graph Python sample.

Initial upload of the drop-graph Python sample.

---

neo4j-to-neptune/readme.md

*Issue #, if available:* Fixed broken link to command doc

Fix link in readme

---

glue-neptune/readme.md

No issue documented.
Fixed broken link in readme, and corrected the title of the recommended alternative library.

Fixed broken link in readme

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

Update Lambda to Python 3.8

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/ApplicationRunner.java
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RefreshAgentDemo.java
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RollingSubsetOfEndpointDemo.java
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/ClusterEndpointsRefreshAgent.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsSelector.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneGremlinClusterBuilder.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneInstanceProperties.java
neptune-gremlin-client/pom.xml

Refactor package to software.amazon.neptune

---

neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPropertyGraphPrinter.java

Ensure to and from IDs quoted in edge CSV file

---

neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RefreshAgentDemo.java
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RollingSubsetOfEndpointDemo.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/ClusterEndpointsRefreshAgent.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneInstanceProperties.java
neptune-gremlin-client/readme.md

Fix Available status check issue

---

neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPropertyGraphPrinter.java

Format CSV representation of IDs and labels like other string values

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json
export-neptune-to-elasticsearch/lambda/export_neptune_to_kinesis.py

Supply additional params to neptune-export when exporting to ES

---

neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NeptuneStreamsJsonPropertyGraphPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/metadata/PropertyTypeInfo.java

…mixed types. For Neptune Streams JSON, publish each value with its own specific type.

Identify broadest type for set cardinality property values

---

neptune-gremlin-client/cloudformation-templates/neptune-endpoints-info-lambda.json
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/lambda/NeptuneGremlinClientExampleLambda.java
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RefreshAgentDemo.java
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RollingSubsetOfEndpointDemo.java
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/GremlinClient.java
neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/GremlinCluster.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/lambda/ClusterEndpointsLambda.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/ClusterEndpointsFetchStrategy.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/ClusterEndpointsRefreshAgent.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsSelector.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsType.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromLambdaProxy.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApi.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneInstanceProperties.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/OnNewAddresses.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/utils/EnvironmentVariableUtils.java
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/src/main/java/software/amazon/lambda/NeptuneEndpointsInfoLambda.java
neptune-gremlin-client/pom.xml
neptune-gremlin-client/readme.md

*Description of changes:* Add endpoints info Lambda proxy for Lambda scenarios

Updates to Neptune gremlin client

---

neptune-python-utils/neptune_python_utils/endpoints.py
neptune-python-utils/neptune_python_utils/gremlin_utils.py

Lazily generate IAM DB Auth signing headers when WS connection is opened

---

neptune-python-utils/neptune_python_utils/bulkload.py
neptune-python-utils/neptune_python_utils/endpoints.py

Pass additional HTTP headers into Endpoint.prepare_request()

---

neptune-export/docs/add-clone.md
neptune-export/docs/create-pg-config.md
neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/docs/export-rdf.md
neptune-export/docs/remove-clone.md
neptune-export/src/main/java/com/amazonaws/services/neptune/AddClone.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NeptuneGremlinClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NodesClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryTask.java

Add --timeout-millis option to export-pg-from-queries

---

neptune-python-utils/build.sh
release.sh

Add neptune-python-utils to release

---

neptune-python-utils/neptune_python_utils/endpoints.py

Refactor LazyHeaders

---

neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/RdfTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportService.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/util/S3ObjectInfo.java
neptune-export/src/test/java/com/amazonaws/services/neptune/util/S3ObjectInfoTest.java

Neptune export updates

---

neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApi.java

Return list of previous addresses while Management API throttled

---

neptune-export/src/main/java/com/amazonaws/services/neptune/AddClone.java
neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportRdfGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/GetClusterInfo.java
neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportBaseCommand.java
neptune-export/src/main/java/com/amazonaws/services/neptune/RemoveClone.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CloneClusterModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CommonConnectionModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/LabModeModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphConcurrencyModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphMetadataSamplingModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphRangeModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphScopeModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphSerializationModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/RdfTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphExportFormat.java
neptune-export/src/test/java/com/amazonaws/services/neptune/util/S3ObjectInfoTest.java

Edit command and parameter descriptions

---

neptune-python-utils/build.sh

Updated build file

---

export-neptune-to-elasticsearch/readme.md

Fix link to CFN template in readme

---

csv-gremlin/README.md
csv-gremlin/csv-gremlin.py

Upload a new tool csv-gremlin, that is able to convert Amazon Neptune CSV format data into Gremlin steps that can be used to load the same data via queries.

Csv gremlin

---

csv-gremlin/README.md
csv-gremlin/csv-gremlin.py
csv-gremlin/test.csv
csv-gremlin/teste.csv

Add command line arguments to allow specification of batch sizes. Add two small sample CSV files. Update the README with information about the new switches.

Add command line options and sample files

---

csv-gremlin/README.md
csv-gremlin/csv-gremlin.py
csv-gremlin/test-files/edges-with-bad-header.csv
csv-gremlin/test-files/edges.csv
csv-gremlin/test-files/vertices-quotes.csv
csv-gremlin/test-files/vertices-with-bad-header.csv

- Fixes a bug where edge IDs were missing the `V()` wrapper. This prevented Gremlin edge creating files from loading.
- Added a new option to escape dollar signs in the output
- Improved processing of different flavors of quoted strings and escaped quotes
- Updated the readme with additional documentation

Csv gremlin edge bug

---

csv-gremlin/csv-gremlin.py
csv-gremlin/test-files/vertices-quotes.csv

- Add support for columns of the form `"Happy \"New\" Year"` that were previously not parsed correctly.
- Add additional tests to cover this case and related ones.

Further improvements to escaped character processing

---

csv-gremlin/csv-gremlin.py

- Generate a more user friendly error message if the CSV file cannot be opened for any reason.

Improve error message if the CSV fails to load

---

neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/Label.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/SpecifiedLabels.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/JsonPropertyGraphPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/JsonResource.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/LabelTest.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/SpecifiedLabelsTest.java

Improve filtering of edges from config file

---

export-neptune-to-elasticsearch/lambda/export_neptune_to_kinesis.py

Delete old version of neptune-export.jar before downloading new version

---

neptune-streams-utils/examples/java8/build.sh
neptune-streams-utils/examples/java8/install-dependencies.sh
neptune-streams-utils/examples/java8/pom.xml
neptune-streams-utils/examples/java8/readme.md
neptune-streams-utils/examples/java8/src/main/java/stream_handler/AbstractStreamHandler.java
neptune-streams-utils/examples/java8/src/main/java/stream_handler/StreamHandler.java
neptune-streams-utils/examples/java8/src/main/java/utils/EnvironmentVariablesUtils.java
neptune-streams-utils/examples/python3.8/build.sh
neptune-streams-utils/examples/python3.8/stream_handler.py
neptune-streams-utils/examples/streams-to-firehose/build.sh
neptune-streams-utils/examples/streams-to-firehose/readme.md
neptune-streams-utils/examples/streams-to-firehose/stream_handler.py
neptune-streams-utils/provisioning/provision_neptune_streams_handler.py
neptune-streams-utils/provisioning/readme.md
neptune-streams-utils/readme.md

Add neptune-stream-utils

---

neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/metadata/DataType.java
neo4j-to-neptune/src/main/java/com/amazonaws/services/neptune/util/CSVUtils.java

Improve performance of type inferencing

---

neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphSchemaInferencingModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Stream.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/ExportStats.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/NeptuneGremlinClient.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/Scope.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphTargetConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/ExportSpecification.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/NeptuneSparqlClient.java

*Description of changes:* Export improvements and fixes

Neptune export 05022021

---

export-neptune-to-elasticsearch/lambda/kinesis_to_elasticsearch.py

Improved logging in Kinsesis-to-Elasticsearch Lambda

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json
export-neptune-to-elasticsearch/lambda/export_neptune_to_kinesis.py
export-neptune-to-elasticsearch/readme.md

Support for large properties and filtering of export

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json
export-neptune-to-elasticsearch/cloudformation-templates/neptune-export-recommend-ebs-volume-size-stack.json
export-neptune-to-elasticsearch/lambda/export_neptune_to_kinesis.py
export-neptune-to-elasticsearch/lambda/kinesis_to_elasticsearch.py

Support Neptune datasets > 1TB

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

Point bucket version to V1 in for lambda poller libraries

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

Bump version of Lambda artifacts to "release_2021_05_19"

Bump version of Lambda artifacts to "release_2021_05_19"

---

neptune-python-utils/build.sh
neptune-python-utils/neptune_python_utils/endpoints.py

Update so that neptune-python-utils with gremlin-python 3.5.0 works with Glue

---

neptune-python-utils/neptune_python_utils/batch_utils.py
neptune-python-utils/neptune_python_utils/glue_gremlin_client.py
neptune-python-utils/neptune_python_utils/mappings.py
neptune-python-utils/readme.md

BatchUtils allows you to create well-formed batch upsert requests, and reproduce updateSingleCardinalityProperties behaviours on upsert.

Added BatchUtils and on_upsert property behaviours

---

neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/lambda/NeptuneGremlinClientExampleLambda.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromLambdaProxy.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromNeptuneManagementApi.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/utils/RegionUtils.java
neptune-gremlin-client/pom.xml

Improve region support when creating refresh agent and lambda proxy

---

neptune-python-utils/neptune_python_utils/batch_utils.py
neptune-python-utils/neptune_python_utils/glue_gremlin_client.py
neptune-python-utils/readme.md

Improve connection handling and retries in BatchUtils

---

neptune-export/docs/create-pg-config.md
neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/docs/export-rdf.md
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/RdfExportScopeModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/ExportRdfFromQuery.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/RdfExportScope.java

Support export from SPARQL query

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/LBAwareHandshakeInterceptor.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneGremlinClusterBuilder.java
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Release 1.0.0 of Gremlin Client for Amazon Neptune

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Bumps Neptune Gremlin Client version to 1.0.1-SNAPSHOT

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

*Issue #, if available:* 149
*Description of changes:* Remove dependency on parent pom in Neptune Gremlin Client

Remove dependency on parent pom in Neptune Gremlin Client

---

neptune-streams-utils/examples/python3.8/build.sh
neptune-streams-utils/examples/streams-to-firehose/build.sh

Update Python build scripts to support gremlin-python 3.5.0

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml
neptune-gremlin-client/readme.md

Bumps Neptune Gremlin Client version to 1.0.2-SNAPSHOT

---

neptune-gremlin-client/readme.md

Update code samples in Neptune Gremlin Client readme

---

neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromGremlinQueries.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphExportFormat.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphTargetConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/RewriteAndMergeCsv.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/GraphSchema.java

Remove duplicate headers from consolidated files in neptune-export

---

neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/DirectoryStructure.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NeptuneStreamsSimpleJsonPropertyGraphPrinter.java

Write simple streams JSON to 'records' directory

---

neptune-export/docs/create-pg-config.md
neptune-export/docs/export-pg-from-config.md
neptune-export/docs/export-pg-from-queries.md
neptune-export/docs/export-pg.md
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PrinterOptionsModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPrinterOptions.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/CsvPropertyGraphPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/DataType.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/schema/DataTypeTest.java

Add option for escaping newline character in CSV exports

---

neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/ConnectionConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportService.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/DirectoryStructure.java
neptune-export/src/main/java/com/amazonaws/services/neptune/profiles/incremental_export/IncrementalExportEventHandler.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NeptuneStreamsJsonPropertyGraphPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NeptuneStreamsSimpleJsonPropertyGraphPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/DataType.java

Ensure all values in simple stream format are written as strings

---

neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/DataType.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/schema/DataTypeTest.java

Fix datetime formatting regression

---

neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/TupleQueryHandler.java

Improve feedback if SPARQL query does not return spog

---

neptune-python-utils/neptune_python_utils/bulkload.py
neptune-python-utils/neptune_python_utils/endpoints.py
neptune-python-utils/neptune_python_utils/glue_neptune_connection_info.py
neptune-python-utils/neptune_python_utils/gremlin_utils.py
neptune-python-utils/readme.md

Support proxies in neptune-python-utils

---

neptune-export/src/main/java/com/amazonaws/services/neptune/CreatePropertyGraphExportConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraph.java
neptune-export/src/main/java/com/amazonaws/services/neptune/ExportPropertyGraphFromConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/StreamRecordsNotFoundExceptionParser.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/ExportToS3NeptuneExportEventHandler.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/FeatureToggle.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/PrintOutputWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/ExportStats.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/DeletableFile.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphExportFormat.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphTargetConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/QueryTask.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/RewriteAndMergeCsv.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/RewriteCsv.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/ExportSpecification.java
neptune-export/src/test/java/com/amazonaws/services/neptune/io/DirectoriesTest.java

neptune-export: Unique suffixes for all files.

---

neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportCommand.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportRunner.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportService.java
neptune-export/src/main/java/com/amazonaws/services/neptune/profiles/neptune_ml/NeptuneMachineLearningExportEventHandlerV2.java

Return non-zero exit code when error occurs while running on command line

---

neptune-export/src/main/java/com/amazonaws/services/neptune/NeptuneExportCommand.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/AwsCliModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CloneClusterModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CommonConnectionModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/GraphSchemaProviderModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/GremlinFiltersModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PrinterOptionsModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphConcurrencyModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphRangeModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphSchemaInferencingModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphScopeModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphSerializationModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/PropertyGraphTargetModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Directories.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/Status.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/ExportPropertyGraphJob.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/NeptuneStreamsSimpleJsonPropertyGraphPrinter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/PropertyGraphTargetConfig.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/NeptuneStreamsSimpleJsonNQuadsWriter.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/io/JsonPropertyGraphPrinterTest.java

Improve logging and error messages

---

neptune-streams-utils/examples/java8/pom.xml
neptune-streams-utils/examples/java8/src/main/java/stream_handler/AbstractStreamHandler.java
neptune-streams-utils/examples/java8/src/main/java/stream_handler/StreamHandler.java

Remove dependency on log4j

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/GremlinClient.java
neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/GremlinClusterBuilder.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsType.java
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Improve event handling when errors occur choosing connection

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsType.java
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml
neptune-gremlin-client/readme.md

Snapshot commit

---

neptune-export/src/main/java/com/amazonaws/services/neptune/export/ExportToS3NeptuneExportEventHandler.java

Log completion file destination

---

neptune-gremlin-client/.gitignore
neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Made some adjustments to the various pom.xml files the most important of which fixes a general compilation problem. Bumped to TinkerPop 3.4.13 and latest version of jackson to resolve some CVE.

Bumped to TinkerPop 3.4.13

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

*Issue #, if available:* #185
*Description of changes:* Update release version in s3 path corresponding to new lambda artifacts of neptune-to-elasticsearch.

Update release version in s3 path for Neptune to ES lambda artifacts

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

*Issue #, if available:* 
N/A
*Description of changes:* 
Update python version and release version in s3 path for lambda artifacts of neptune-to-elasticsearch

Update versions for Neptune to ES lambda artifacts

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

Update version of stream poller artifacts to release_2022_07_25

Update version of stream poller artifacts.

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json

Update version of stream poller artefacts to release_2022_07_27

---

neptune-export/readme.md

*Issue #, if available:* Related to #238
Update documentation about concurrency and queriesFile argument.

Add notes about concurrency and queriesFile

---

neptune-export/src/main/java/com/amazonaws/services/neptune/GetClusterInfo.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cli/CloneClusterModule.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/GetLastEventId.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/NeptuneClusterMetadata.java

*Description of changes:* Log cluster details prior to triggering cloning and export.

Log source cluster details at beginning of export

---

neptune-python-utils/build-lambda-layer.sh

Add Lambda layer build script for neptune-python-utils.

Add Lambda layer build script for neptune-python-utils.

---

neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/GetEndpointsFromLambdaProxy.java

Meaningful error message when Lambda proxy doesn't support returning JSON.

---

neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/NeptuneClusterMetadata.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/EndpointValidator.java

Validate endpoints when inferring cluster ID

---

neptune-export/pom.xml
neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportLambda.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/NeptuneExportRunner.java
neptune-export/src/main/java/com/amazonaws/services/neptune/util/GitProperties.java

*Description of changes:* Print details of the latest Git commit of neptune-export.jar at the beginning of an export.

Output Git info at start of export

---

neptune-export/pom.xml
neptune-export/src/main/java/com/amazonaws/services/neptune/RunNeptuneExportSvc.java
neptune-export/src/main/java/com/amazonaws/services/neptune/cluster/HttpResponse.java
neptune-export/src/main/java/com/amazonaws/services/neptune/export/Args.java
neptune-export/src/main/java/com/amazonaws/services/neptune/io/FileToStreamOutputWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/JsonResource.java
neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/GraphElementSchemas.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/NeptuneStreamsJsonNQuadsWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/rdf/io/NeptuneStreamsSimpleJsonNQuadsWriter.java
neptune-export/src/main/java/com/amazonaws/services/neptune/util/NotImplementedException.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/RangeFactoryTest.java
neptune-export/src/test/java/com/amazonaws/services/neptune/propertygraph/io/CsvPropertyGraphPrinterTest.java

Neptune export update dependencies

---

neptune-python-utils/neptune_python_utils/batch_utils.py
neptune-python-utils/neptune_python_utils/gremlin_utils.py
neptune-python-utils/neptune_python_utils/mappings.py
neptune-python-utils/readme.md

Addresses https://github.com/awslabs/amazon-neptune-tools/issues/277

Support multi-valued properties in batch utils

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Neptune Gremlin Client 1.0.7

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Update Neptune Gremlin Client version to 1.0.8-SNAPSHOT

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Neptune Gremlin Client release 1.0.8

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml
neptune-gremlin-client/readme.md

Update Neptune Gremlin Client version to 1.0.9-SNAPSHOT

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json
export-neptune-to-elasticsearch/lambda/requirements.txt
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml

Update Export Neptune to ES Lambdas for Python 3.9

---

neptune-python-utils/neptune_python_utils/streams.py

Added all_records_after method to NeptuneStream client

---

neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml

Update Lambda pom to point to latest client release

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/ApplicationRunner.java

Update logging in Neptune Gremlin Client demo

---

neptune-gremlin-client/readme.md

Updated Neptune Gremlin Client docs

---

neptune-gremlin-client/cloudformation-templates/neptune-endpoints-info-lambda.json
neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client-demo/src/main/java/software/amazon/neptune/RollingSubsetOfEndpointDemo.java
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/gremlin-client/src/main/java/org/apache/tinkerpop/gremlin/driver/GremlinClient.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/EndpointsType.java
neptune-gremlin-client/gremlin-client/src/main/java/software/amazon/neptune/cluster/NeptuneGremlinClusterBuilder.java
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/src/main/java/software/amazon/lambda/NeptuneEndpointsInfoLambda.java
neptune-gremlin-client/pom.xml
neptune-gremlin-client/readme.md

Version 1.1.0-SNAPSHOT – Allow marking endpoints as unavailable in Lambda proxy

---

neptune-export/readme.md

Adding a deprecation notice to neptune-export indicating the migration to a new standalone repository.

Adding deprecation notice to neptune-export readme

---

neptune-python-utils/neptune_python_utils/endpoints.py
neptune-python-utils/neptune_python_utils/gremlin_utils.py

Support adding headers to LazyHttpHeaders

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml

Release 1.1.0 of Neptune Gremlin Client

---

neptune-gremlin-client/gremlin-client-demo/pom.xml
neptune-gremlin-client/gremlin-client/pom.xml
neptune-gremlin-client/neptune-endpoints-info-lambda/pom.xml
neptune-gremlin-client/pom.xml
neptune-gremlin-client/readme.md

Neptune gremlin client 1 1 1 snapshot

---

neptune-serverless-evaluator/LICENSE
neptune-serverless-evaluator/README.md
neptune-serverless-evaluator/pricing.py
neptune-serverless-evaluator/requirements.txt

checks cw metrics data and evaluated is serverless is cheaper to run than provisioned and the other way round

checks for serverless vs provisioned

---

dynamic-custom-endpoints/cloudformation-templates/dynamic-custom-endpoints-lambda.json
dynamic-custom-endpoints/lambda/build.sh
dynamic-custom-endpoints/lambda/dynamic-custom-endpoints/build.sh
dynamic-custom-endpoints/lambda/dynamic-custom-endpoints/dynamic_custom_endpoints.py
dynamic-custom-endpoints/readme.md

*Description of changes:* Added dynamic-custom-endpoints project

Added dynamic-custom-endpoints

---

neo4j-to-neptune/readme.md

Corrected Neptune to Neo4j
Simple change from Neptune to Neo4j

Corrected Neptune to Neo4j in readme.md

---

export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json
export-neptune-to-elasticsearch/lambda/kinesis_to_elasticsearch.py

Update to stream poller handlers to release_2023_09_04 which includes support for opensearch serverless. Updates the kinesis-to-elasticsearch execution role to grant access to AOSS updates the calls to the es_handler due to API changes in the update.

Support for Opensearch Serverless

---

export-neptune-to-elasticsearch/lambda/kinesis_to_elasticsearch.py

Resolving an issue from the recent update of the elasticsearch/opensearch handlers in which the queries were no longer being correctly written to opensearch. These changes have been tested for gremlin and sparql exports to both standard opensearch as well as opensearch serverless.

Fix opensearch query execution with updated elasticsearch handler

---

export-neptune-to-elasticsearch/readme.md

Updating the readme with instructions for updating the data access policy for Amazon OpenSearch Serverless users. Also included is an update to the regional cloudformation deployment table to include new regions.

Add OpenSearch Serverless instructions to ReadMe
